services:
  frontend:
    build: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: db-57xsl
  db:
    image: mariadb:10.6.4-focal
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=db-57xsl
    restart: always
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: {}
    